apiVersion: v1
kind: Pod
metadata:
  name: pod6
spec:
  containers:
    - name: pythonappcontainer
      image: tuuobit/pythonapp:latest # replace with your image name
      stdin: true          # allows interactive input
      tty: true            # enables an interactive terminal